Repository mongodb/docs-csharp, pull requests merged in 2024-12, with the labels that each got.

#342 DOCSP-44706 - Type discriminator note
  source/fundamentals/serialization/polymorphic-objects.txt
  source/upgrade/v3.txt
  source/whats-new.txt
Labels: backport v3.0

#348 DOCSP-45824 Remove broken GUID link
  source/fundamentals/serialization/guid-serialization.txt
Labels: backport v3.0, backport v3.1

#361 DOCSP-45009 - Cluster Monitoring
  source/fundamentals.txt
  source/fundamentals/monitoring.txt
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22, backport v3.1

#379 DOCSP-45870 - Parallelism note
  source/fundamentals/transactions.txt
Labels: backport v3.0, backport v3.1

#365 DOCSP-41170 - Clarify string ID generation
  source/fundamentals/serialization/poco.txt
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22, backport v3.1

#373 DOCSP-40066: Support SelectMany inside Project/Select
  source/fundamentals/linq.txt
  source/includes/fundamentals/code-examples/linq.cs
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v3.1

#295 DOCSP-38064 - Arrays
  config/redirects
  snooty.toml
  source/fundamentals/crud/write-operations.txt
  source/fundamentals/crud/write-operations/bulk-write.txt
  source/fundamentals/crud/write-operations/modify.txt
  source/fundamentals/crud/write-operations/replace.txt
  source/fundamentals/crud/write-operations/update-many.txt
  source/fundamentals/crud/write-operations/update-many/arrays.txt
  source/fundamentals/crud/write-operations/update-many/fields.txt
  source/fundamentals/crud/write-operations/update-one.txt
  source/fundamentals/crud/write-operations/update-one/arrays.txt
  source/fundamentals/crud/write-operations/update-one/fields.txt
  source/includes/atlas-sample-data.rst
  source/includes/code-examples/replace-one/ReplaceOne.cs
  source/includes/code-examples/replace-one/ReplaceOneAsync.cs
  source/includes/code-examples/update-many/UpdateMany.cs
  source/includes/code-examples/update-many/UpdateManyArrays.cs
  source/includes/code-examples/update-one/UpdateOne.cs
  source/includes/code-examples/update-one/UpdateOneArrays.cs
  source/includes/code-examples/update-one/UpdateOneAsync.cs
  source/includes/method-overloads.rst
  source/includes/page-templates/update/arrays.rst
  source/includes/page-templates/update/fields.rst
  source/includes/page-templates/update/update.rst
  source/includes/update-arrays-positional-operator-note.rst
  source/includes/update-many/allpositional-linq-code-intro.rst
  source/includes/update-many/allpositional-operator-code-intro.rst
  source/includes/update-many/filteredpositional-linq-code-intro.rst
  source/includes/update-many/filteredpositional-operator-code-intro.rst
  source/includes/update-many/positional-linq-code-intro.rst
  source/includes/update-many/positional-operator-code-intro.rst
  source/includes/update-one/allpositional-linq-code-intro.rst
  source/includes/update-one/allpositional-operator-code-intro.rst
  source/includes/update-one/filteredpositional-linq-code-intro.rst
  source/includes/update-one/filteredpositional-operator-code-intro.rst
  source/includes/update-one/positional-linq-code-intro.rst
  source/includes/update-one/positional-operator-code-intro.rst
  source/quick-reference.txt
  source/upgrade/v2.txt
  source/usage-examples/updateMany.txt
  source/usage-examples/updateOne.txt
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22, backport v3.1
