Repository mongodb/docs-csharp, pull requests merged in 2024-11, with the labels that each got.

#296 DOCSP-44897 TOC relabel V3.0
  source/fundamentals.txt
  source/fundamentals/connection.txt
  source/fundamentals/crud.txt
  source/fundamentals/crud/read-operations.txt
  source/fundamentals/crud/write-operations.txt
  source/fundamentals/serialization.txt
  source/index.txt
  source/upgrade.txt
  source/usage-examples.txt
Labels: backport v2.30

#299 Temporary includes fix
  source/compatibility.txt
  source/fundamentals/encrypt-fields.txt
  source/includes/include-fixes/compatibility-table-legend.rst
  source/includes/include-fixes/encrypt-fields.rst
  source/includes/include-fixes/lifecycle-schedule-callout.rst
Labels: backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22

#300 Temporary includes fix (#299)
  source/compatibility.txt
  source/fundamentals/encrypt-fields.txt
  source/includes/include-fixes/compatibility-table-legend.rst
  source/includes/include-fixes/encrypt-fields.rst
  source/includes/include-fixes/lifecycle-schedule-callout.rst
Labels: backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22

#298 DOCSP-45443 Remaining TOC Changes
  source/fundamentals/crud/read-operations.txt
Labels: backport v2.29, backport v2.28, backport v2.27

#311 [Backport v2.29] DOCSP-44897 TOC Relabel (#287)
  source/fundamentals.txt
  source/fundamentals/connection.txt
  source/fundamentals/crud.txt
  source/fundamentals/crud/write-operations.txt
  source/fundamentals/serialization.txt
  source/index.txt
  source/upgrade.txt
  source/usage-examples.txt
Labels: backport v2.30, backport v2.28, backport v2.27

#284 Authentication refactor
  config/redirects
  snooty.toml
  source/connection-troubleshooting.txt
  source/fundamentals.txt
  source/fundamentals/authentication.txt
  source/fundamentals/authentication/aws-iam.txt
  source/fundamentals/authentication/kerberos.txt
  source/fundamentals/authentication/ldap.txt
  source/fundamentals/authentication/oidc.txt
  source/fundamentals/authentication/scram.txt
  source/fundamentals/authentication/x509.txt
  source/fundamentals/enterprise-authentication.txt
  source/includes/comma-auth-options.rst
  source/includes/troubleshooting/x509.rst
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26

#289 DOCSP-39980 - GridFS
  source/fundamentals.txt
  source/fundamentals/crud/write-operations/insert.txt
  source/fundamentals/gridfs.txt
  source/includes/code-examples/GridFS.cs
  source/includes/figures/GridFS-upload.png
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22

#331 DOCSP-45691 - Fix TOC
  source/fundamentals.txt
Labels: backport v3.0

#332 DOCSP-45693 - Remove EOL docs from What's New
  source/whats-new.txt
Labels: backport v3.0, backport v2.30, backport v2.29, backport v2.28, backport v2.27, backport v2.26, backport v2.25, backport v2.24, backport v2.23, backport v2.22
